with-expecter: true
dir: internal/domain/interface/mocks
outpkg: mocks
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceNameSnake}}.go"
packages:
  github.com/james-hsueh/crontab-watcher/internal/domain/interface:
    config:
      all: true
