// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIIdentifierGenerator is an autogenerated mock type for the IIdentifierGenerator type
type MockIIdentifierGenerator struct {
	mock.Mock
}

type MockIIdentifierGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIIdentifierGenerator) EXPECT() *MockIIdentifierGenerator_Expecter {
	return &MockIIdentifierGenerator_Expecter{mock: &_m.Mock}
}

// NewIdentifier provides a mock function with no fields
func (_m *MockIIdentifierGenerator) NewIdentifier() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewIdentifier")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIIdentifierGenerator_NewIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewIdentifier'
type MockIIdentifierGenerator_NewIdentifier_Call struct {
	*mock.Call
}

// NewIdentifier is a helper method to define mock.On call
func (_e *MockIIdentifierGenerator_Expecter) NewIdentifier() *MockIIdentifierGenerator_NewIdentifier_Call {
	return &MockIIdentifierGenerator_NewIdentifier_Call{Call: _e.mock.On("NewIdentifier")}
}

func (_c *MockIIdentifierGenerator_NewIdentifier_Call) Run(run func()) *MockIIdentifierGenerator_NewIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIIdentifierGenerator_NewIdentifier_Call) Return(_a0 string) *MockIIdentifierGenerator_NewIdentifier_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIIdentifierGenerator_NewIdentifier_Call) RunAndReturn(run func() string) *MockIIdentifierGenerator_NewIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIIdentifierGenerator creates a new instance of MockIIdentifierGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIIdentifierGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIIdentifierGenerator {
	mock := &MockIIdentifierGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
