// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	time "time"

	vo "github.com/james-hsueh/crontab-watcher/internal/domain/vo"
	mock "github.com/stretchr/testify/mock"
)

// MockICommandExecutionProxy is an autogenerated mock type for the ICommandExecutionProxy type
type MockICommandExecutionProxy struct {
	mock.Mock
}

type MockICommandExecutionProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICommandExecutionProxy) EXPECT() *MockICommandExecutionProxy_Expecter {
	return &MockICommandExecutionProxy_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, command, timeout
func (_m *MockICommandExecutionProxy) Execute(ctx context.Context, command string, timeout time.Duration) (vo.CommandExecutionResult, error) {
	ret := _m.Called(ctx, command, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 vo.CommandExecutionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (vo.CommandExecutionResult, error)); ok {
		return rf(ctx, command, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) vo.CommandExecutionResult); ok {
		r0 = rf(ctx, command, timeout)
	} else {
		r0 = ret.Get(0).(vo.CommandExecutionResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, command, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICommandExecutionProxy_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockICommandExecutionProxy_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - command string
//   - timeout time.Duration
func (_e *MockICommandExecutionProxy_Expecter) Execute(ctx interface{}, command interface{}, timeout interface{}) *MockICommandExecutionProxy_Execute_Call {
	return &MockICommandExecutionProxy_Execute_Call{Call: _e.mock.On("Execute", ctx, command, timeout)}
}

func (_c *MockICommandExecutionProxy_Execute_Call) Run(run func(ctx context.Context, command string, timeout time.Duration)) *MockICommandExecutionProxy_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockICommandExecutionProxy_Execute_Call) Return(_a0 vo.CommandExecutionResult, _a1 error) *MockICommandExecutionProxy_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICommandExecutionProxy_Execute_Call) RunAndReturn(run func(context.Context, string, time.Duration) (vo.CommandExecutionResult, error)) *MockICommandExecutionProxy_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICommandExecutionProxy creates a new instance of MockICommandExecutionProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICommandExecutionProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICommandExecutionProxy {
	mock := &MockICommandExecutionProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
