// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockICrondReloadProxy is an autogenerated mock type for the ICrondReloadProxy type
type MockICrondReloadProxy struct {
	mock.Mock
}

type MockICrondReloadProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICrondReloadProxy) EXPECT() *MockICrondReloadProxy_Expecter {
	return &MockICrondReloadProxy_Expecter{mock: &_m.Mock}
}

// Reload provides a mock function with given fields: crontabFilePath
func (_m *MockICrondReloadProxy) Reload(crontabFilePath string) error {
	ret := _m.Called(crontabFilePath)

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(crontabFilePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICrondReloadProxy_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type MockICrondReloadProxy_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
//   - crontabFilePath string
func (_e *MockICrondReloadProxy_Expecter) Reload(crontabFilePath interface{}) *MockICrondReloadProxy_Reload_Call {
	return &MockICrondReloadProxy_Reload_Call{Call: _e.mock.On("Reload", crontabFilePath)}
}

func (_c *MockICrondReloadProxy_Reload_Call) Run(run func(crontabFilePath string)) *MockICrondReloadProxy_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockICrondReloadProxy_Reload_Call) Return(_a0 error) *MockICrondReloadProxy_Reload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICrondReloadProxy_Reload_Call) RunAndReturn(run func(string) error) *MockICrondReloadProxy_Reload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICrondReloadProxy creates a new instance of MockICrondReloadProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICrondReloadProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICrondReloadProxy {
	mock := &MockICrondReloadProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
