// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	vo "github.com/james-hsueh/crontab-watcher/internal/domain/vo"
	mock "github.com/stretchr/testify/mock"
)

// MockIJobLogRepository is an autogenerated mock type for the IJobLogRepository type
type MockIJobLogRepository struct {
	mock.Mock
}

type MockIJobLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJobLogRepository) EXPECT() *MockIJobLogRepository_Expecter {
	return &MockIJobLogRepository_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: filePath, content
func (_m *MockIJobLogRepository) Append(filePath string, content string) error {
	ret := _m.Called(filePath, content)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(filePath, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIJobLogRepository_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockIJobLogRepository_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - filePath string
//   - content string
func (_e *MockIJobLogRepository_Expecter) Append(filePath interface{}, content interface{}) *MockIJobLogRepository_Append_Call {
	return &MockIJobLogRepository_Append_Call{Call: _e.mock.On("Append", filePath, content)}
}

func (_c *MockIJobLogRepository_Append_Call) Run(run func(filePath string, content string)) *MockIJobLogRepository_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIJobLogRepository_Append_Call) Return(_a0 error) *MockIJobLogRepository_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIJobLogRepository_Append_Call) RunAndReturn(run func(string, string) error) *MockIJobLogRepository_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Tail provides a mock function with given fields: filePath, lines
func (_m *MockIJobLogRepository) Tail(filePath string, lines int) (vo.JobLogTail, error) {
	ret := _m.Called(filePath, lines)

	if len(ret) == 0 {
		panic("no return value specified for Tail")
	}

	var r0 vo.JobLogTail
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (vo.JobLogTail, error)); ok {
		return rf(filePath, lines)
	}
	if rf, ok := ret.Get(0).(func(string, int) vo.JobLogTail); ok {
		r0 = rf(filePath, lines)
	} else {
		r0 = ret.Get(0).(vo.JobLogTail)
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(filePath, lines)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIJobLogRepository_Tail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tail'
type MockIJobLogRepository_Tail_Call struct {
	*mock.Call
}

// Tail is a helper method to define mock.On call
//   - filePath string
//   - lines int
func (_e *MockIJobLogRepository_Expecter) Tail(filePath interface{}, lines interface{}) *MockIJobLogRepository_Tail_Call {
	return &MockIJobLogRepository_Tail_Call{Call: _e.mock.On("Tail", filePath, lines)}
}

func (_c *MockIJobLogRepository_Tail_Call) Run(run func(filePath string, lines int)) *MockIJobLogRepository_Tail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockIJobLogRepository_Tail_Call) Return(_a0 vo.JobLogTail, _a1 error) *MockIJobLogRepository_Tail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIJobLogRepository_Tail_Call) RunAndReturn(run func(string, int) (vo.JobLogTail, error)) *MockIJobLogRepository_Tail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIJobLogRepository creates a new instance of MockIJobLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJobLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJobLogRepository {
	mock := &MockIJobLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
