// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockINotificationProxy is an autogenerated mock type for the INotificationProxy type
type MockINotificationProxy struct {
	mock.Mock
}

type MockINotificationProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockINotificationProxy) EXPECT() *MockINotificationProxy_Expecter {
	return &MockINotificationProxy_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function with given fields: title, body
func (_m *MockINotificationProxy) Notify(title string, body string) error {
	ret := _m.Called(title, body)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(title, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockINotificationProxy_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockINotificationProxy_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - title string
//   - body string
func (_e *MockINotificationProxy_Expecter) Notify(title interface{}, body interface{}) *MockINotificationProxy_Notify_Call {
	return &MockINotificationProxy_Notify_Call{Call: _e.mock.On("Notify", title, body)}
}

func (_c *MockINotificationProxy_Notify_Call) Run(run func(title string, body string)) *MockINotificationProxy_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockINotificationProxy_Notify_Call) Return(_a0 error) *MockINotificationProxy_Notify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockINotificationProxy_Notify_Call) RunAndReturn(run func(string, string) error) *MockINotificationProxy_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockINotificationProxy creates a new instance of MockINotificationProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockINotificationProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockINotificationProxy {
	mock := &MockINotificationProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
