// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "github.com/james-hsueh/crontab-watcher/internal/domain/entity"

	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockIJobRunRepository is an autogenerated mock type for the IJobRunRepository type
type MockIJobRunRepository struct {
	mock.Mock
}

type MockIJobRunRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJobRunRepository) EXPECT() *MockIJobRunRepository_Expecter {
	return &MockIJobRunRepository_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: run
func (_m *MockIJobRunRepository) Append(run *entity.JobRun) error {
	ret := _m.Called(run)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.JobRun) error); ok {
		r0 = rf(run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIJobRunRepository_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockIJobRunRepository_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - run *entity.JobRun
func (_e *MockIJobRunRepository_Expecter) Append(run interface{}) *MockIJobRunRepository_Append_Call {
	return &MockIJobRunRepository_Append_Call{Call: _e.mock.On("Append", run)}
}

func (_c *MockIJobRunRepository_Append_Call) Run(run func(run *entity.JobRun)) *MockIJobRunRepository_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.JobRun))
	})
	return _c
}

func (_c *MockIJobRunRepository_Append_Call) Return(_a0 error) *MockIJobRunRepository_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIJobRunRepository_Append_Call) RunAndReturn(run func(*entity.JobRun) error) *MockIJobRunRepository_Append_Call {
	_c.Call.Return(run)
	return _c
}

// HasRunningRun provides a mock function with given fields: jobID
func (_m *MockIJobRunRepository) HasRunningRun(jobID string) (bool, error) {
	ret := _m.Called(jobID)

	if len(ret) == 0 {
		panic("no return value specified for HasRunningRun")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(jobID)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(jobID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIJobRunRepository_HasRunningRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRunningRun'
type MockIJobRunRepository_HasRunningRun_Call struct {
	*mock.Call
}

// HasRunningRun is a helper method to define mock.On call
//   - jobID string
func (_e *MockIJobRunRepository_Expecter) HasRunningRun(jobID interface{}) *MockIJobRunRepository_HasRunningRun_Call {
	return &MockIJobRunRepository_HasRunningRun_Call{Call: _e.mock.On("HasRunningRun", jobID)}
}

func (_c *MockIJobRunRepository_HasRunningRun_Call) Run(run func(jobID string)) *MockIJobRunRepository_HasRunningRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIJobRunRepository_HasRunningRun_Call) Return(_a0 bool, _a1 error) *MockIJobRunRepository_HasRunningRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIJobRunRepository_HasRunningRun_Call) RunAndReturn(run func(string) (bool, error)) *MockIJobRunRepository_HasRunningRun_Call {
	_c.Call.Return(run)
	return _c
}

// LatestByJobIDs provides a mock function with given fields: jobIDs
func (_m *MockIJobRunRepository) LatestByJobIDs(jobIDs []string) (map[string]*entity.JobRun, error) {
	ret := _m.Called(jobIDs)

	if len(ret) == 0 {
		panic("no return value specified for LatestByJobIDs")
	}

	var r0 map[string]*entity.JobRun
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (map[string]*entity.JobRun, error)); ok {
		return rf(jobIDs)
	}
	if rf, ok := ret.Get(0).(func([]string) map[string]*entity.JobRun); ok {
		r0 = rf(jobIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*entity.JobRun)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(jobIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIJobRunRepository_LatestByJobIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestByJobIDs'
type MockIJobRunRepository_LatestByJobIDs_Call struct {
	*mock.Call
}

// LatestByJobIDs is a helper method to define mock.On call
//   - jobIDs []string
func (_e *MockIJobRunRepository_Expecter) LatestByJobIDs(jobIDs interface{}) *MockIJobRunRepository_LatestByJobIDs_Call {
	return &MockIJobRunRepository_LatestByJobIDs_Call{Call: _e.mock.On("LatestByJobIDs", jobIDs)}
}

func (_c *MockIJobRunRepository_LatestByJobIDs_Call) Run(run func(jobIDs []string)) *MockIJobRunRepository_LatestByJobIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockIJobRunRepository_LatestByJobIDs_Call) Return(_a0 map[string]*entity.JobRun, _a1 error) *MockIJobRunRepository_LatestByJobIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIJobRunRepository_LatestByJobIDs_Call) RunAndReturn(run func([]string) (map[string]*entity.JobRun, error)) *MockIJobRunRepository_LatestByJobIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListByJobID provides a mock function with given fields: jobID, limit
func (_m *MockIJobRunRepository) ListByJobID(jobID string, limit int) ([]*entity.JobRun, error) {
	ret := _m.Called(jobID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByJobID")
	}

	var r0 []*entity.JobRun
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]*entity.JobRun, error)); ok {
		return rf(jobID, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []*entity.JobRun); ok {
		r0 = rf(jobID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.JobRun)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(jobID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIJobRunRepository_ListByJobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByJobID'
type MockIJobRunRepository_ListByJobID_Call struct {
	*mock.Call
}

// ListByJobID is a helper method to define mock.On call
//   - jobID string
//   - limit int
func (_e *MockIJobRunRepository_Expecter) ListByJobID(jobID interface{}, limit interface{}) *MockIJobRunRepository_ListByJobID_Call {
	return &MockIJobRunRepository_ListByJobID_Call{Call: _e.mock.On("ListByJobID", jobID, limit)}
}

func (_c *MockIJobRunRepository_ListByJobID_Call) Run(run func(jobID string, limit int)) *MockIJobRunRepository_ListByJobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockIJobRunRepository_ListByJobID_Call) Return(_a0 []*entity.JobRun, _a1 error) *MockIJobRunRepository_ListByJobID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIJobRunRepository_ListByJobID_Call) RunAndReturn(run func(string, int) ([]*entity.JobRun, error)) *MockIJobRunRepository_ListByJobID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRunningRunsAsInterrupted provides a mock function with given fields: interruptedAt
func (_m *MockIJobRunRepository) MarkRunningRunsAsInterrupted(interruptedAt time.Time) (int, error) {
	ret := _m.Called(interruptedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkRunningRunsAsInterrupted")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) (int, error)); ok {
		return rf(interruptedAt)
	}
	if rf, ok := ret.Get(0).(func(time.Time) int); ok {
		r0 = rf(interruptedAt)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(interruptedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRunningRunsAsInterrupted'
type MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call struct {
	*mock.Call
}

// MarkRunningRunsAsInterrupted is a helper method to define mock.On call
//   - interruptedAt time.Time
func (_e *MockIJobRunRepository_Expecter) MarkRunningRunsAsInterrupted(interruptedAt interface{}) *MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call {
	return &MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call{Call: _e.mock.On("MarkRunningRunsAsInterrupted", interruptedAt)}
}

func (_c *MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call) Run(run func(interruptedAt time.Time)) *MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call) Return(_a0 int, _a1 error) *MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call) RunAndReturn(run func(time.Time) (int, error)) *MockIJobRunRepository_MarkRunningRunsAsInterrupted_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: run
func (_m *MockIJobRunRepository) Update(run *entity.JobRun) error {
	ret := _m.Called(run)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.JobRun) error); ok {
		r0 = rf(run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIJobRunRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIJobRunRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - run *entity.JobRun
func (_e *MockIJobRunRepository_Expecter) Update(run interface{}) *MockIJobRunRepository_Update_Call {
	return &MockIJobRunRepository_Update_Call{Call: _e.mock.On("Update", run)}
}

func (_c *MockIJobRunRepository_Update_Call) Run(run func(run *entity.JobRun)) *MockIJobRunRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.JobRun))
	})
	return _c
}

func (_c *MockIJobRunRepository_Update_Call) Return(_a0 error) *MockIJobRunRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIJobRunRepository_Update_Call) RunAndReturn(run func(*entity.JobRun) error) *MockIJobRunRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIJobRunRepository creates a new instance of MockIJobRunRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJobRunRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJobRunRepository {
	mock := &MockIJobRunRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
