// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "github.com/james-hsueh/crontab-watcher/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockICrontabDocumentRepository is an autogenerated mock type for the ICrontabDocumentRepository type
type MockICrontabDocumentRepository struct {
	mock.Mock
}

type MockICrontabDocumentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICrontabDocumentRepository) EXPECT() *MockICrontabDocumentRepository_Expecter {
	return &MockICrontabDocumentRepository_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with no fields
func (_m *MockICrontabDocumentRepository) Load() (*entity.CrontabDocument, string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *entity.CrontabDocument
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func() (*entity.CrontabDocument, string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *entity.CrontabDocument); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CrontabDocument)
		}
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICrontabDocumentRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockICrontabDocumentRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockICrontabDocumentRepository_Expecter) Load() *MockICrontabDocumentRepository_Load_Call {
	return &MockICrontabDocumentRepository_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockICrontabDocumentRepository_Load_Call) Run(run func()) *MockICrontabDocumentRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockICrontabDocumentRepository_Load_Call) Return(_a0 *entity.CrontabDocument, _a1 string, _a2 error) *MockICrontabDocumentRepository_Load_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICrontabDocumentRepository_Load_Call) RunAndReturn(run func() (*entity.CrontabDocument, string, error)) *MockICrontabDocumentRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: document, expectedFingerprint
func (_m *MockICrontabDocumentRepository) Save(document *entity.CrontabDocument, expectedFingerprint string) error {
	ret := _m.Called(document, expectedFingerprint)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.CrontabDocument, string) error); ok {
		r0 = rf(document, expectedFingerprint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICrontabDocumentRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockICrontabDocumentRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - document *entity.CrontabDocument
//   - expectedFingerprint string
func (_e *MockICrontabDocumentRepository_Expecter) Save(document interface{}, expectedFingerprint interface{}) *MockICrontabDocumentRepository_Save_Call {
	return &MockICrontabDocumentRepository_Save_Call{Call: _e.mock.On("Save", document, expectedFingerprint)}
}

func (_c *MockICrontabDocumentRepository_Save_Call) Run(run func(document *entity.CrontabDocument, expectedFingerprint string)) *MockICrontabDocumentRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.CrontabDocument), args[1].(string))
	})
	return _c
}

func (_c *MockICrontabDocumentRepository_Save_Call) Return(_a0 error) *MockICrontabDocumentRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICrontabDocumentRepository_Save_Call) RunAndReturn(run func(*entity.CrontabDocument, string) error) *MockICrontabDocumentRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICrontabDocumentRepository creates a new instance of MockICrontabDocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICrontabDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICrontabDocumentRepository {
	mock := &MockICrontabDocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
